name: flutter-cli
on: push


jobs:
  build-and-test:
    name: build and test app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        uses: steebchen/flutter@v1.1.0
        with:
          args: pub get

      - name: run tests
        uses: steebchen/flutter@v1.1.0
        with:
          args: test

      - name: build apk
        uses: steebchen/flutter@v1.1.0
        with:
          args: build apk --release

  build-ios:
    name: Build iOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign

  build-windows:
    name: Build Windows app
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows

  build-macos:
    name: Build macOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos


